export const liveMatches = [
  {
    id: "l1",
    homeTeam: "Brazil",
    awayTeam: "Argentina",
    homeFlag: "🇧🇷",
    awayFlag: "🇦🇷",
    homeScore: 2,
    awayScore: 1,
    status: "live",
    minute: 67,
    date: "2026-06-15",
    time: "20:00",
    venue: "SoFi Stadium",
    city: "Los Angeles",
    round: "Group Stage",
    group: "Group C",
  },
  {
    id: "l2",
    homeTeam: "France",
    awayTeam: "Germany",
    homeFlag: "🇫🇷",
    awayFlag: "🇩🇪",
    homeScore: 1,
    awayScore: 1,
    status: "live",
    minute: 43,
    date: "2026-06-15",
    time: "20:00",
    venue: "MetLife Stadium",
    city: "New York",
    round: "Group Stage",
    group: "Group A",
  },
];

export const upcomingMatches = [
  {
    id: "u1",
    homeTeam: "Spain",
    awayTeam: "Portugal",
    homeFlag: "🇪🇸",
    awayFlag: "🇵🇹",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    date: "2026-06-16",
    time: "15:00",
    venue: "AT&T Stadium",
    city: "Dallas",
    round: "Group Stage",
    group: "Group B",
  },
  {
    id: "u2",
    homeTeam: "England",
    awayTeam: "Netherlands",
    homeFlag: "🏴",
    awayFlag: "🇳🇱",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    date: "2026-06-16",
    time: "18:00",
    venue: "Levi's Stadium",
    city: "San Francisco",
    round: "Group Stage",
    group: "Group D",
  },
  {
    id: "u3",
    homeTeam: "USA",
    awayTeam: "Mexico",
    homeFlag: "🇺🇸",
    awayFlag: "🇲🇽",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    date: "2026-06-16",
    time: "21:00",
    venue: "Estadio Azteca",
    city: "Mexico City",
    round: "Group Stage",
    group: "Group E",
  },
  {
    id: "u4",
    homeTeam: "Japan",
    awayTeam: "South Korea",
    homeFlag: "🇯🇵",
    awayFlag: "🇰🇷",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    date: "2026-06-17",
    time: "12:00",
    venue: "BC Place",
    city: "Vancouver",
    round: "Group Stage",
    group: "Group F",
  },
  {
    id: "u5",
    homeTeam: "Morocco",
    awayTeam: "Senegal",
    homeFlag: "🇲🇦",
    awayFlag: "🇸🇳",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    date: "2026-06-17",
    time: "15:00",
    venue: "BMO Field",
    city: "Toronto",
    round: "Group Stage",
    group: "Group G",
  },
  {
    id: "u6",
    homeTeam: "Italy",
    awayTeam: "Belgium",
    homeFlag: "🇮🇹",
    awayFlag: "🇧🇪",
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    date: "2026-06-17",
    time: "21:00",
    venue: "Arrowhead Stadium",
    city: "Kansas City",
    round: "Group Stage",
    group: "Group H",
  },
];

export const allFixtures = [
  ...liveMatches,
  ...upcomingMatches,
  {
    id: "f1",
    homeTeam: "Canada",
    awayTeam: "Chile",
    homeFlag: "🇨🇦",
    awayFlag: "🇨🇱",
    homeScore: 3,
    awayScore: 0,
    status: "finished",
    date: "2026-06-14",
    time: "18:00",
    venue: "BMO Field",
    city: "Toronto",
    round: "Group Stage",
    group: "Group A",
  },
  {
    id: "f2",
    homeTeam: "Portugal",
    awayTeam: "Poland",
    homeFlag: "🇵🇹",
    awayFlag: "🇵🇱",
    homeScore: 2,
    awayScore: 2,
    status: "finished",
    date: "2026-06-14",
    time: "21:00",
    venue: "Lincoln Financial Field",
    city: "Philadelphia",
    round: "Group Stage",
    group: "Group B",
  },
  {
    id: "f3",
    homeTeam: "Netherlands",
    awayTeam: "Ecuador",
    homeFlag: "🇳🇱",
    awayFlag: "🇪🇨",
    homeScore: 4,
    awayScore: 1,
    status: "finished",
    date: "2026-06-14",
    time: "15:00",
    venue: "Rose Bowl",
    city: "Pasadena",
    round: "Group Stage",
    group: "Group D",
  },
  {
    id: "f4",
    homeTeam: "Australia",
    awayTeam: "Iran",
    homeFlag: "🇦🇺",
    awayFlag: "🇮🇷",
    homeScore: 1,
    awayScore: 0,
    status: "finished",
    date: "2026-06-13",
    time: "20:00",
    venue: "NRG Stadium",
    city: "Houston",
    round: "Group Stage",
    group: "Group F",
  },
];

export const groups = [
  {
    name: "Group A",
    teams: [
      { team: "France", flag: "🇫🇷", played: 2, won: 1, drawn: 1, lost: 0, gf: 4, ga: 2, gd: 2, points: 4 },
      { team: "Germany", flag: "🇩🇪", played: 2, won: 1, drawn: 1, lost: 0, gf: 3, ga: 2, gd: 1, points: 4 },
      { team: "Canada", flag: "🇨🇦", played: 2, won: 1, drawn: 0, lost: 1, gf: 3, ga: 2, gd: 1, points: 3 },
      { team: "Chile", flag: "🇨🇱", played: 2, won: 0, drawn: 0, lost: 2, gf: 0, ga: 4, gd: -4, points: 0 },
    ],
  },
  {
    name: "Group B",
    teams: [
      { team: "Spain", flag: "🇪🇸", played: 2, won: 2, drawn: 0, lost: 0, gf: 5, ga: 1, gd: 4, points: 6 },
      { team: "Portugal", flag: "🇵🇹", played: 2, won: 1, drawn: 1, lost: 0, gf: 4, ga: 3, gd: 1, points: 4 },
      { team: "Poland", flag: "🇵🇱", played: 2, won: 0, drawn: 1, lost: 1, gf: 3, ga: 5, gd: -2, points: 1 },
      { team: "Qatar", flag: "🇶🇦", played: 2, won: 0, drawn: 0, lost: 2, gf: 1, ga: 4, gd: -3, points: 0 },
    ],
  },
  {
    name: "Group C",
    teams: [
      { team: "Brazil", flag: "🇧🇷", played: 2, won: 2, drawn: 0, lost: 0, gf: 6, ga: 2, gd: 4, points: 6 },
      { team: "Argentina", flag: "🇦🇷", played: 2, won: 1, drawn: 0, lost: 1, gf: 4, ga: 4, gd: 0, points: 3 },
      { team: "Colombia", flag: "🇨🇴", played: 2, won: 1, drawn: 0, lost: 1, gf: 3, ga: 3, gd: 0, points: 3 },
      { team: "Nigeria", flag: "🇳🇬", played: 2, won: 0, drawn: 0, lost: 2, gf: 2, ga: 6, gd: -4, points: 0 },
    ],
  },
  {
    name: "Group D",
    teams: [
      { team: "Netherlands", flag: "🇳🇱", played: 2, won: 2, drawn: 0, lost: 0, gf: 7, ga: 2, gd: 5, points: 6 },
      { team: "England", flag: "🏴", played: 2, won: 1, drawn: 0, lost: 1, gf: 4, ga: 3, gd: 1, points: 3 },
      { team: "Ecuador", flag: "🇪🇨", played: 2, won: 1, drawn: 0, lost: 1, gf: 3, ga: 5, gd: -2, points: 3 },
      { team: "Tunisia", flag: "🇹🇳", played: 2, won: 0, drawn: 0, lost: 2, gf: 1, ga: 5, gd: -4, points: 0 },
    ],
  },
  {
    name: "Group E",
    teams: [
      { team: "USA", flag: "🇺🇸", played: 1, won: 1, drawn: 0, lost: 0, gf: 2, ga: 0, gd: 2, points: 3 },
      { team: "Mexico", flag: "🇲🇽", played: 1, won: 0, drawn: 1, lost: 0, gf: 1, ga: 1, gd: 0, points: 1 },
      { team: "Uruguay", flag: "🇺🇾", played: 1, won: 0, drawn: 1, lost: 0, gf: 1, ga: 1, gd: 0, points: 1 },
      { team: "Saudi Arabia", flag: "🇸🇦", played: 1, won: 0, drawn: 0, lost: 1, gf: 0, ga: 2, gd: -2, points: 0 },
    ],
  },
  {
    name: "Group F",
    teams: [
      { team: "Japan", flag: "🇯🇵", played: 1, won: 1, drawn: 0, lost: 0, gf: 3, ga: 1, gd: 2, points: 3 },
      { team: "Australia", flag: "🇦🇺", played: 1, won: 1, drawn: 0, lost: 0, gf: 1, ga: 0, gd: 1, points: 3 },
      { team: "South Korea", flag: "🇰🇷", played: 1, won: 0, drawn: 0, lost: 1, gf: 1, ga: 3, gd: -2, points: 0 },
      { team: "Iran", flag: "🇮🇷", played: 1, won: 0, drawn: 0, lost: 1, gf: 0, ga: 1, gd: -1, points: 0 },
    ],
  },
  {
    name: "Group G",
    teams: [
      { team: "Morocco", flag: "🇲🇦", played: 1, won: 1, drawn: 0, lost: 0, gf: 2, ga: 0, gd: 2, points: 3 },
      { team: "Croatia", flag: "🇭🇷", played: 1, won: 1, drawn: 0, lost: 0, gf: 2, ga: 1, gd: 1, points: 3 },
      { team: "Senegal", flag: "🇸🇳", played: 1, won: 0, drawn: 0, lost: 1, gf: 0, ga: 2, gd: -2, points: 0 },
      { team: "Denmark", flag: "🇩🇰", played: 1, won: 0, drawn: 0, lost: 1, gf: 1, ga: 2, gd: -1, points: 0 },
    ],
  },
  {
    name: "Group H",
    teams: [
      { team: "Italy", flag: "🇮🇹", played: 1, won: 1, drawn: 0, lost: 0, gf: 3, ga: 0, gd: 3, points: 3 },
      { team: "Switzerland", flag: "🇨🇭", played: 1, won: 1, drawn: 0, lost: 0, gf: 2, ga: 1, gd: 1, points: 3 },
      { team: "Belgium", flag: "🇧🇪", played: 1, won: 0, drawn: 0, lost: 1, gf: 0, ga: 3, gd: -3, points: 0 },
      { team: "Cameroon", flag: "🇨🇲", played: 1, won: 0, drawn: 0, lost: 1, gf: 1, ga: 2, gd: -1, points: 0 },
    ],
  },
];

export const bracketRounds = [
  {
    round: "Round of 32",
    matches: [
      { id: "r32-1", homeTeam: "France", awayTeam: "Ecuador", homeFlag: "🇫🇷", awayFlag: "🇪🇨", homeScore: 3, awayScore: 0, status: "finished", round: "Round of 32" },
      { id: "r32-2", homeTeam: "Spain", awayTeam: "South Korea", homeFlag: "🇪🇸", awayFlag: "🇰🇷", homeScore: 2, awayScore: 1, status: "finished", round: "Round of 32" },
      { id: "r32-3", homeTeam: "Brazil", awayTeam: "Denmark", homeFlag: "🇧🇷", awayFlag: "🇩🇰", homeScore: 4, awayScore: 1, status: "finished", round: "Round of 32" },
      { id: "r32-4", homeTeam: "Netherlands", awayTeam: "Cameroon", homeFlag: "🇳🇱", awayFlag: "🇨🇲", homeScore: 3, awayScore: 1, status: "finished", round: "Round of 32" },
      { id: "r32-5", homeTeam: "Germany", awayTeam: "Tunisia", homeFlag: "🇩🇪", awayFlag: "🇹🇳", homeScore: 2, awayScore: 0, status: "finished", round: "Round of 32" },
      { id: "r32-6", homeTeam: "Argentina", awayTeam: "Saudi Arabia", homeFlag: "🇦🇷", awayFlag: "🇸🇦", homeScore: 3, awayScore: 0, status: "finished", round: "Round of 32" },
      { id: "r32-7", homeTeam: "England", awayTeam: "Iran", homeFlag: "🏴", awayFlag: "🇮🇷", homeScore: 2, awayScore: 0, status: "finished", round: "Round of 32" },
      { id: "r32-8", homeTeam: "Morocco", awayTeam: "Australia", homeFlag: "🇲🇦", awayFlag: "🇦🇺", homeScore: 1, awayScore: 0, status: "finished", round: "Round of 32" },
    ],
  },
  {
    round: "Round of 16",
    matches: [
      { id: "r16-1", homeTeam: "France", awayTeam: "Spain", homeFlag: "🇫🇷", awayFlag: "🇪🇸", homeScore: 2, awayScore: 1, status: "finished", round: "Round of 16" },
      { id: "r16-2", homeTeam: "Brazil", awayTeam: "Netherlands", homeFlag: "🇧🇷", awayFlag: "🇳🇱", homeScore: 2, awayScore: 2, status: "finished", round: "Round of 16" },
      { id: "r16-3", homeTeam: "Germany", awayTeam: "Argentina", homeFlag: "🇩🇪", awayFlag: "🇦🇷", homeScore: null, awayScore: null, status: "upcoming", round: "Round of 16" },
      { id: "r16-4", homeTeam: "England", awayTeam: "Morocco", homeFlag: "🏴", awayFlag: "🇲🇦", homeScore: null, awayScore: null, status: "upcoming", round: "Round of 16" },
    ],
  },
  {
    round: "Quarter Finals",
    matches: [
      { id: "qf-1", homeTeam: "France", awayTeam: "Brazil", homeFlag: "🇫🇷", awayFlag: "🇧🇷", homeScore: null, awayScore: null, status: "upcoming", round: "Quarter Finals" },
      { id: "qf-2", homeTeam: "TBD", awayTeam: "TBD", homeFlag: "🏳️", awayFlag: "🏳️", homeScore: null, awayScore: null, status: "upcoming", round: "Quarter Finals" },
    ],
  },
  {
    round: "Semi Finals",
    matches: [
      { id: "sf-1", homeTeam: "TBD", awayTeam: "TBD", homeFlag: "🏳️", awayFlag: "🏳️", homeScore: null, awayScore: null, status: "upcoming", round: "Semi Finals" },
    ],
  },
  {
    round: "Final",
    matches: [
      { id: "final", homeTeam: "TBD", awayTeam: "TBD", homeFlag: "🏳️", awayFlag: "🏳️", homeScore: null, awayScore: null, status: "upcoming", round: "Final" },
    ],
  },
];